version: '3'
services:

  jenkins:
    container_name: jenkins
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - ./docker/jenkins/:/var/jekins_home
    networks:
      - jenkins

networks:
  jenkins:
    driver: bridge      
